--CASO 1
SELECT TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUN CLIENTE",
INITCAP(C.PNOMBRE)||' '||INITCAP(C.SNOMBRE)||' '||INITCAP(C.APPATERNO)||' '||INITCAP(C.APMATERNO) AS "NOMBRE CLIENTE",
EXTRACT(DAY FROM FECHA_NACIMIENTO)||' de '||TO_CHAR(FECHA_NACIMIENTO,'month') AS "FECHA DE NACIMIENTO",
C.DIRECCION||'/'||UPPER(R.NOMBRE_REGION)
FROM CLIENTE C
JOIN REGION R ON R.COD_REGION = C.COD_REGION
WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) = 9
--WHERE EXTRACT(MONTH FROM FECHA_NACIMIENTO) = EXTRACT(MONTH FROM SYSDATE)+1
ORDER BY "FECHA DE NACIMIENTO" DESC ,APPATERNO ASC;

--CASO 2
SELECT TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN AS "RUT CLIENTE",
C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO AS "NOMBRE CLIENTE",
TO_CHAR(SUM(TTC.MONTO_TRANSACCION),'$99G999G999') AS "MONTO COMPRAS",
TO_CHAR((SUM(TTC.MONTO_TRANSACCION)/10000)*250,'$99G999G999') AS "PUNTOS"
FROM CLIENTE C
INNER JOIN TARJETA_CLIENTE TC ON TC.NUMRUN = C.NUMRUN
INNER JOIN TRANSACCION_TARJETA_CLIENTE TTC ON TTC.NRO_TARJETA = TC.NRO_TARJETA
WHERE EXTRACT(YEAR FROM TTC.FECHA_TRANSACCION) = 2021
GROUP BY C.NUMRUN,C.DVRUN,C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO
ORDER BY "MONTO COMPRAS"
;