--CASO 1 INFORME 1
SELECT TS.DESCRIPCION||','||S.DESCRIPCION AS "SISTEMA SALUD",
        COUNT(A.ATE_ID) AS "CANTIDAD DE PACIENTE"
FROM ATENCION A
JOIN PACIENTE P ON A.PAC_RUN = P.PAC_RUN
JOIN SALUD S ON P.SAL_ID = S.SAL_ID
JOIN TIPO_SALUD TS ON S.TIPO_SAL_ID = TS.TIPO_SAL_ID
WHERE TS.TIPO_SAL_ID IN ('F','I')
AND EXTRACT(YEAR FROM FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)
AND EXTRACT(MONTH FROM FECHA_ATENCION) = EXTRACT(MONTH FROM SYSDATE)-1
GROUP BY TS.DESCRIPCION||','||S.DESCRIPCION
HAVING COUNT(A.ATE_ID) > (SELECT 
                          ROUND(AVG(COUNT(ATE_ID)))
                          FROM ATENCION
                          WHERE EXTRACT(YEAR FROM FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)
                          AND EXTRACT(MONTH FROM FECHA_ATENCION) = EXTRACT(MONTH FROM SYSDATE)-1
                          GROUP BY FECHA_ATENCION)
ORDER BY "SISTEMA SALUD";

--CASO 1 INFORME 2
SELECT TO_CHAR(A.PAC_RUN,'09G999G999')||'-'||P.DV_RUN AS "RUT PACIENTE",
P.PNOMBRE||' '||P.SNOMBRE||' '||P.APATERNO||' '||P.AMATERNO AS "NOMBRE PACIENTE",
P.EDAD,
'Le corresponde un '||PO.PORCENTAJE_DESCTO||'% de descuento en la primera consulta medica del año '||EXTRACT(YEAR FROM SYSDATE) AS "PORCENTAJE DESCUENTO"
FROM ATENCION A 
JOIN (SELECT PAC_RUN,DV_RUN,PNOMBRE,SNOMBRE,APATERNO,AMATERNO,
        ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) AS "EDAD"
        FROM PACIENTE P
        WHERE ROUND(MONTHS_BETWEEN(SYSDATE,FECHA_NACIMIENTO)/12) >= 65) P ON A.PAC_RUN = P.PAC_RUN
JOIN PORC_DESCTO_3RA_EDAD PO ON P.EDAD BETWEEN PO.ANNO_INI AND PO.ANNO_TER
WHERE EXTRACT(YEAR FROM A.FECHA_ATENCION) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY A.PAC_RUN,P.DV_RUN,P.PNOMBRE,P.SNOMBRE,P.APATERNO,P.AMATERNO,P.EDAD,PO.PORCENTAJE_DESCTO
HAVING COUNT(A.PAC_RUN) > 4;